/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ronierejr
 */
public class EmprestimoView extends javax.swing.JPanel {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmprestimoView.class.getName());

    /**
     * Creates new form EmprestimoView
     */
    public EmprestimoView() {
        initComponents();
        estilizarCabecalho();
        estilizarPagina();
    }
    
     private dao.EmprestimoDAO emprestimDAO = new dao.EmprestimoDAO();
        private models.Usuario usuarioLogado;

        public void setUsuarioLogado(models.Usuario usuario) {
            this.usuarioLogado = usuario;
        }

    private void estilizarPagina() {
        setBackground(new java.awt.Color(247, 248, 250));

        jPanel2.setBackground(new java.awt.Color(247, 248, 250));

        jPanel3.setBackground(new java.awt.Color(247, 248, 250));

        estilizarBotao(btnDevolver, new java.awt.Color(46, 196, 182));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(229, 231, 235)
        ));

        tabelaEmprestimos.getTableHeader().setBackground(new java.awt.Color(26, 26, 46));
        tabelaEmprestimos.getTableHeader().setFont(
            new java.awt.Font("SansSerif", java.awt.Font.BOLD, 12)
        );
        tabelaEmprestimos.setRowHeight(32);
        tabelaEmprestimos.setGridColor(new java.awt.Color(229, 231, 235));
    }
    private void estilizarCabecalho() {
        
        jPanel1.setBackground(new java.awt.Color(102,102,255));


        estilizarBotao(btnNovo, new java.awt.Color(67, 97, 238));
        estilizarBotao(btnTodos, new java.awt.Color(67, 97, 238));
        estilizarBotao(btnAtivos, new java.awt.Color(46, 196, 182));
        estilizarBotao(btnAtrasados, new java.awt.Color(230, 57, 70));
    }

    private void estilizarBotao(javax.swing.JButton btn, java.awt.Color cor) {
        btn.setBackground(cor);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnTodos = new javax.swing.JButton();
        btnAtivos = new javax.swing.JButton();
        btnAtrasados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEmprestimos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 680));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        lblTitulo.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lblTitulo.setText("Empréstimos");
        jPanel4.add(lblTitulo);

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        btnTodos.setText("Todos");
        btnTodos.addActionListener(this::btnTodosActionPerformed);
        jPanel5.add(btnTodos);

        btnAtivos.setText("Ativos");
        btnAtivos.addActionListener(this::btnAtivosActionPerformed);
        jPanel5.add(btnAtivos);

        btnAtrasados.setText("Atrasados");
        btnAtrasados.addActionListener(this::btnAtrasadosActionPerformed);
        jPanel5.add(btnAtrasados);

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.CardLayout(100, 20));

        tabelaEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ISBN", "CPF Membro", "Data Empréstimo", "Prev. Devolução", "Devolução Real", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelaEmprestimos);

        jPanel2.add(jScrollPane1, "card2");

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(1, 40, 30));

        btnNovo.setText("+ Novo Empréstimo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        jPanel3.add(btnNovo);

        btnDevolver.setText("Registrar Devolução");
        btnDevolver.addActionListener(this::btnDevolverActionPerformed);
        jPanel3.add(btnDevolver);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        JDialog dialog = new JDialog();
        dialog.setTitle("Novo Empréstimo");
        dialog.setSize(450, 350);
        dialog.setModal(true);
        dialog.setLocationRelativeTo(this);

        JPanel painel = new JPanel(new GridLayout(6, 2, 10, 10));
        painel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JTextField fId = new JTextField();
        JTextField fIsbn = new JTextField();
        JTextField fCpf = new JTextField();
        JTextField fDataEmp = new JTextField();
        JTextField fPrevDev = new JTextField();

        painel.add(new JLabel("ID:"));
        painel.add(fId);

        painel.add(new JLabel("ISBN:"));
        painel.add(fIsbn);

        painel.add(new JLabel("CPF Membro:"));
        painel.add(fCpf);

        painel.add(new JLabel("Data Empréstimo:"));
        painel.add(fDataEmp);

        painel.add(new JLabel("Prev. Devolução:"));
        painel.add(fPrevDev);

        JButton btnSalvar = new JButton("Salvar");

        btnSalvar.addActionListener(e -> {

            DefaultTableModel modelo =
                    (DefaultTableModel) tabelaEmprestimos.getModel();

            modelo.addRow(new Object[]{
                fId.getText(),
                fIsbn.getText(),
                fCpf.getText(),
                fDataEmp.getText(),
                fPrevDev.getText(),
                "",
                "Ativo"
            });

            JOptionPane.showMessageDialog(dialog,
                    "Empréstimo registrado com sucesso!");

            dialog.dispose();
        });

        painel.add(new JLabel());
        painel.add(btnSalvar);

        dialog.add(painel);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        int row = tabelaEmprestimos.getSelectedRow();

            if (row < 0) {
                JOptionPane.showMessageDialog(this,
                        "Selecione um empréstimo.");
                return;
            }

            DefaultTableModel modelo =
                    (DefaultTableModel) tabelaEmprestimos.getModel();

            String dataHoje =
                    java.time.LocalDate.now().toString();

            modelo.setValueAt(dataHoje, row, 5);
            modelo.setValueAt("Devolvido", row, 6);

            JOptionPane.showMessageDialog(this,
                    "Devolução registrada com sucesso!");
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        DefaultTableModel modelo =
                (DefaultTableModel) tabelaEmprestimos.getModel();

        TableRowSorter<DefaultTableModel> sorter =
                new TableRowSorter<>(modelo);

        tabelaEmprestimos.setRowSorter(sorter);

        sorter.setRowFilter(null);
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivosActionPerformed
        DefaultTableModel modelo =
                (DefaultTableModel) tabelaEmprestimos.getModel();

        TableRowSorter<DefaultTableModel> sorter =
                new TableRowSorter<>(modelo);

        tabelaEmprestimos.setRowSorter(sorter);
        
        sorter.setRowFilter(
        RowFilter.regexFilter("^Ativo$", 6)
    );
    }//GEN-LAST:event_btnAtivosActionPerformed

    private void btnAtrasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasadosActionPerformed
        DefaultTableModel modelo =
                (DefaultTableModel) tabelaEmprestimos.getModel();

        TableRowSorter<DefaultTableModel> sorter =
                new TableRowSorter<>(modelo);

        tabelaEmprestimos.setRowSorter(sorter);
        
        sorter.setRowFilter(
        RowFilter.regexFilter("^Atrasado$", 6)
    );
    }//GEN-LAST:event_btnAtrasadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmprestimoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtivos;
    private javax.swing.JButton btnAtrasados;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabelaEmprestimos;
    // End of variables declaration//GEN-END:variables
}
