/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.GridLayout;
import java.time.LocalDate;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import controllers.EmprestimoController;
import controllers.LivroController;
import controllers.MembroController;
import models.Emprestimo;
import models.Livro;
import models.Membro;

/**
 *
 * @author ronierejr
 */
public class EmprestimoView extends javax.swing.JPanel {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(EmprestimoView.class.getName());

    /**
     * Creates new form EmprestimoView
     */
    public EmprestimoView() {
        initComponents();
        estilizarCabecalho();
        estilizarPagina();
        carregarTabela();

        btnFiltrarMembro.addActionListener(e -> filtrarPorMembro());
        btnLimparFiltro.addActionListener(e -> carregarTabela());
    }

    private EmprestimoController emprestimoController = new EmprestimoController();
    private LivroController livroController = new LivroController();
    private MembroController membroController = new MembroController();
    private models.Usuario usuarioLogado;

    public void setUsuarioLogado(models.Usuario usuario) {
        this.usuarioLogado = usuario;
    }

    private void estilizarPagina() {
        setBackground(new java.awt.Color(247, 248, 250));

        jPanel2.setBackground(new java.awt.Color(247, 248, 250));

        jPanel3.setBackground(new java.awt.Color(247, 248, 250));

        estilizarBotao(btnDevolver, new java.awt.Color(46, 196, 182));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(229, 231, 235)));

        tabelaEmprestimos.getTableHeader().setBackground(new java.awt.Color(26, 26, 46));
        tabelaEmprestimos.getTableHeader().setForeground(java.awt.Color.WHITE);
        tabelaEmprestimos.getTableHeader().setFont(
                new java.awt.Font("SansSerif", java.awt.Font.BOLD, 12));
        tabelaEmprestimos.setRowHeight(32);
        tabelaEmprestimos.setGridColor(new java.awt.Color(229, 231, 235));
    }

    private void estilizarCabecalho() {

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        estilizarBotao(btnNovo, new java.awt.Color(67, 97, 238));
        estilizarBotao(btnTodos, new java.awt.Color(67, 97, 238));
        estilizarBotao(btnAtivos, new java.awt.Color(46, 196, 182));
        estilizarBotao(btnAtrasados, new java.awt.Color(230, 57, 70));
    }

    private void estilizarBotao(javax.swing.JButton btn, java.awt.Color cor) {
        btn.setBackground(cor);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
    }

    public void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaEmprestimos.getModel();
        modelo.setRowCount(0);
        for (Emprestimo e : emprestimoController.listarEmprestimos()) {
            String status = e.isDevolvido() ? "Devolvido" : (e.calcularMulta() > 0 ? "Atrasado" : "Ativo");
            modelo.addRow(new Object[] {
                    e.getLivro().getIsbn(),
                    e.getMembro().getCpf(),
                    e.getDataEmprestimo(),
                    e.getDataDevolucaoPrevista(),
                    e.getDataDevolucaoReal() != null ? e.getDataDevolucaoReal() : "",
                    status
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnTodos = new javax.swing.JButton();
        btnAtivos = new javax.swing.JButton();
        btnAtrasados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEmprestimos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 680));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        lblTitulo.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lblTitulo.setText("Empréstimos");
        jPanel4.add(lblTitulo);

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        btnTodos.setText("Todos");
        btnTodos.addActionListener(this::btnTodosActionPerformed);
        jPanel5.add(btnTodos);

        btnAtivos.setText("Ativos");
        btnAtivos.addActionListener(this::btnAtivosActionPerformed);
        jPanel5.add(btnAtivos);

        btnAtrasados.setText("Atrasados");
        btnAtrasados.addActionListener(this::btnAtrasadosActionPerformed);
        jPanel5.add(btnAtrasados);

        JLabel lblFiltroMembro = new JLabel("CPF Membro:");
        campoFiltroMembro = new JTextField(15);
        btnFiltrarMembro = new JButton("Filtrar");
        btnLimparFiltro = new JButton("Limpar");

        jPanel5.add(lblFiltroMembro);
        jPanel5.add(campoFiltroMembro);
        jPanel5.add(btnFiltrarMembro);
        jPanel5.add(btnLimparFiltro);

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.CardLayout(100, 20));

        tabelaEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "ISBN", "CPF Membro", "Data Empréstimo", "Prev. Devolução", "Devolução Real", "Status"
                }));
        jScrollPane1.setViewportView(tabelaEmprestimos);

        jPanel2.add(jScrollPane1, "card2");

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(1, 40, 30));

        btnNovo.setText("+ Novo Empréstimo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        jPanel3.add(btnNovo);

        btnDevolver.setText("Registrar Devolução");
        btnDevolver.addActionListener(this::btnDevolverActionPerformed);
        jPanel3.add(btnDevolver);

        btnEditar = new javax.swing.JButton();
        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        jPanel3.add(btnEditar);

        btnExcluir = new javax.swing.JButton();
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        jPanel3.add(btnExcluir);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNovoActionPerformed
        JDialog dialog = new JDialog();
        dialog.setTitle("Novo Empréstimo");
        dialog.setSize(400, 250);
        dialog.setModal(true);
        dialog.setLocationRelativeTo(this);

        JPanel painel = new JPanel(new GridLayout(3, 2, 10, 10));
        painel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JTextField fIsbn = new JTextField();
        JTextField fCpf = new JTextField();

        painel.add(new JLabel("ISBN do Livro:"));
        painel.add(fIsbn);
        painel.add(new JLabel("CPF do Membro:"));
        painel.add(fCpf);

        JButton btnSalvar = new JButton("Salvar");
        btnSalvar.setBackground(new java.awt.Color(67, 97, 238));
        btnSalvar.setForeground(java.awt.Color.WHITE);
        btnSalvar.setBorderPainted(false);

        btnSalvar.addActionListener(e -> {
            String isbn = fIsbn.getText().trim();
            String cpf = fCpf.getText().trim();
            if (isbn.isEmpty() || cpf.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "Preencha ISBN e CPF.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Livro livro = livroController.buscarPorIsbn(isbn);
            Membro membro = membroController.buscarPorCpf(cpf);
            if (livro == null) {
                JOptionPane.showMessageDialog(dialog, "Livro não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (membro == null) {
                JOptionPane.showMessageDialog(dialog, "Membro não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean sucesso = emprestimoController.realizarEmprestimo(usuarioLogado, livro, membro);
            if (sucesso) {
                carregarTabela();
                JOptionPane.showMessageDialog(dialog, "Empréstimo realizado com sucesso!", "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                dialog.dispose();
            } else {
                JOptionPane.showMessageDialog(dialog,
                        "Falha ao realizar empréstimo. Verifique se o membro não está suspenso, se já possui o livro ativo ou se há disponibilidade.",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        });

        painel.add(new JLabel());
        painel.add(btnSalvar);
        dialog.add(painel);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnNovoActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDevolverActionPerformed
        int row = tabelaEmprestimos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo.");
            return;
        }
        DefaultTableModel modelo = (DefaultTableModel) tabelaEmprestimos.getModel();
        String isbn = modelo.getValueAt(row, 0).toString();
        String cpf = modelo.getValueAt(row, 1).toString();
        String dataStr = modelo.getValueAt(row, 2).toString();
        LocalDate dataEmprestimo = LocalDate.parse(dataStr);
        Livro livro = livroController.buscarPorIsbn(isbn);
        Membro membro = membroController.buscarPorCpf(cpf);
        if (livro == null || membro == null) {
            JOptionPane.showMessageDialog(this, "Dados inconsistentes.");
            return;
        }
        boolean sucesso = emprestimoController.registrarDevolucao(usuarioLogado, livro, membro, dataEmprestimo);
        if (sucesso) {
            carregarTabela();
            JOptionPane.showMessageDialog(this, "Devolução registrada!");
        }
    }// GEN-LAST:event_btnDevolverActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTodosActionPerformed
        carregarTabela();
    }// GEN-LAST:event_btnTodosActionPerformed

    private void btnAtivosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAtivosActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabelaEmprestimos.getModel();
        modelo.setRowCount(0);
        for (Emprestimo e : emprestimoController.listarEmprestimosAtivos()) {
            modelo.addRow(new Object[] {
                    e.getLivro().getIsbn(), e.getMembro().getCpf(),
                    e.getDataEmprestimo(), e.getDataDevolucaoPrevista(),
                    "", "Ativo"
            });
        }
    }// GEN-LAST:event_btnAtivosActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {
        int row = tabelaEmprestimos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo para editar.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel modelo = (DefaultTableModel) tabelaEmprestimos.getModel();
        String isbn = modelo.getValueAt(row, 0).toString();
        String cpf = modelo.getValueAt(row, 1).toString();
        String dataStr = modelo.getValueAt(row, 2).toString();
        LocalDate dataEmprestimo = LocalDate.parse(dataStr);
        LocalDate dataPrevista = LocalDate.parse(modelo.getValueAt(row, 3).toString());
        String dataRealStr = modelo.getValueAt(row, 4).toString();
        LocalDate dataReal = dataRealStr.isEmpty() ? null : LocalDate.parse(dataRealStr);
        boolean devolvido = "Devolvido".equals(modelo.getValueAt(row, 5));

        Emprestimo alvo = null;
        for (Emprestimo e : emprestimoController.listarEmprestimos()) {
            if (e.getLivro().getIsbn().equals(isbn) && e.getMembro().getCpf().equals(cpf)
                    && e.getDataEmprestimo().equals(dataEmprestimo)) {
                alvo = e;
                break;
            }
        }
        if (alvo == null) {
            JOptionPane.showMessageDialog(this, "Empréstimo não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JDialog dialog = new JDialog();
        dialog.setTitle("Editar Empréstimo");
        dialog.setSize(400, 300);
        dialog.setModal(true);
        dialog.setLocationRelativeTo(this);

        JPanel painel = new JPanel(new GridLayout(5, 2, 10, 10));
        painel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JTextField fDataEmp = new JTextField(dataEmprestimo.toString());
        JTextField fDataPrev = new JTextField(dataPrevista.toString());
        JTextField fDataReal = new JTextField(dataReal != null ? dataReal.toString() : "");
        JCheckBox cbDevolvido = new JCheckBox("Devolvido", devolvido);

        painel.add(new JLabel("Data Empréstimo:"));
        painel.add(fDataEmp);
        painel.add(new JLabel("Prev. Devolução:"));
        painel.add(fDataPrev);
        painel.add(new JLabel("Data Real:"));
        painel.add(fDataReal);
        painel.add(new JLabel("Devolvido:"));
        painel.add(cbDevolvido);

        JButton btnSalvar = new JButton("Salvar");
        final Emprestimo emprestimoAlvo = alvo;
        btnSalvar.addActionListener(e -> {
            try {
                LocalDate novaDataEmp = LocalDate.parse(fDataEmp.getText().trim());
                LocalDate novaDataPrev = LocalDate.parse(fDataPrev.getText().trim());
                LocalDate novaDataReal = fDataReal.getText().trim().isEmpty() ? null
                        : LocalDate.parse(fDataReal.getText().trim());
                boolean novoDevolvido = cbDevolvido.isSelected();
                boolean sucesso = emprestimoController.editarEmprestimo(usuarioLogado, emprestimoAlvo, novaDataEmp,
                        novaDataPrev,
                        novaDataReal, novoDevolvido);
                if (sucesso) {
                    carregarTabela();
                    JOptionPane.showMessageDialog(dialog, "Empréstimo editado!", "Sucesso",
                            JOptionPane.INFORMATION_MESSAGE);
                    dialog.dispose();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog, "Erro ao editar: " + ex.getMessage(), "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        });

        painel.add(new JLabel());
        painel.add(btnSalvar);
        dialog.add(painel);
        dialog.setVisible(true);
    }

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        int row = tabelaEmprestimos.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel modelo = (DefaultTableModel) tabelaEmprestimos.getModel();
        String isbn = modelo.getValueAt(row, 0).toString();
        String cpf = modelo.getValueAt(row, 1).toString();
        String dataStr = modelo.getValueAt(row, 2).toString();
        LocalDate dataEmprestimo = LocalDate.parse(dataStr);

        Emprestimo alvo = null;
        for (Emprestimo e : emprestimoController.listarEmprestimos()) {
            if (e.getLivro().getIsbn().equals(isbn) && e.getMembro().getCpf().equals(cpf)
                    && e.getDataEmprestimo().equals(dataEmprestimo)) {
                alvo = e;
                break;
            }
        }
        if (alvo == null) {
            JOptionPane.showMessageDialog(this, "Empréstimo não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        final Emprestimo emprestimoAlvo = alvo;
        int confirm = JOptionPane.showConfirmDialog(this, "Excluir este empréstimo?", "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            boolean sucesso = emprestimoController.excluirEmprestimo(usuarioLogado, emprestimoAlvo);
            if (sucesso) {
                carregarTabela();
                JOptionPane.showMessageDialog(this, "Empréstimo excluído!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnAtrasadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAtrasadosActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabelaEmprestimos.getModel();
        modelo.setRowCount(0);
        for (Emprestimo e : emprestimoController.listarEmprestimosAtrasados()) {
            modelo.addRow(new Object[] {
                    e.getLivro().getIsbn(), e.getMembro().getCpf(),
                    e.getDataEmprestimo(), e.getDataDevolucaoPrevista(),
                    "", "Atrasado"
            });
        }
    }// GEN-LAST:event_btnAtrasadosActionPerformed

    private void filtrarPorMembro() {
        String cpf = campoFiltroMembro.getText().trim();
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um CPF.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Membro membro = membroController.buscarPorCpf(cpf);
        if (membro == null) {
            JOptionPane.showMessageDialog(this, "Membro não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultTableModel modelo = (DefaultTableModel) tabelaEmprestimos.getModel();
        modelo.setRowCount(0);
        
        for (Emprestimo e : emprestimoController.listarEmprestimosAtivosPorMembro(membro)) {
            modelo.addRow(new Object[] {
                    e.getLivro().getIsbn(),
                    e.getMembro().getCpf(),
                    e.getDataEmprestimo(),
                    e.getDataDevolucaoPrevista(),
                    e.getDataDevolucaoReal() != null ? e.getDataDevolucaoReal() : "",
                    e.isDevolvido() ? "Devolvido" : (e.calcularMulta() > 0 ? "Atrasado" : "Ativo")
            });
        }

        for (Emprestimo e : emprestimoController.listarEmprestimosAtrasadosPorMembro(membro)) {
            modelo.addRow(new Object[] {
                    e.getLivro().getIsbn(),
                    e.getMembro().getCpf(),
                    e.getDataEmprestimo(),
                    e.getDataDevolucaoPrevista(),
                    e.getDataDevolucaoReal() != null ? e.getDataDevolucaoReal() : "",
                    e.isDevolvido() ? "Devolvido" : (e.calcularMulta() > 0 ? "Atrasado" : "Ativo")
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmprestimoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtivos;
    private javax.swing.JButton btnAtrasados;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabelaEmprestimos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JTextField campoFiltroMembro;
    private javax.swing.JButton btnFiltrarMembro;
    private javax.swing.JButton btnLimparFiltro;
    // End of variables declaration//GEN-END:variables
}
