/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.GridLayout;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import controllers.LivroController;
import models.Livro;

/**
 *
 * @author ronierejr
 */
public class LivroView extends javax.swing.JPanel {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(LivroView.class.getName());

    /**
     * Creates new form LivroView
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        campoBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAddCopia = new javax.swing.JButton();
        btnRemCopia = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 680));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(457, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        campoBusca.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        campoBusca.setPreferredSize(new java.awt.Dimension(200, 15));
        campoBusca.addActionListener(this::campoBuscaActionPerformed);
        jPanel4.add(campoBusca);

        btnBuscar.setText("Buscar");
        jPanel4.add(btnBuscar);

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        lblTitulo.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lblTitulo.setText("Acervo de Livros");
        jPanel5.add(lblTitulo);

        jPanel1.add(jPanel5, java.awt.BorderLayout.WEST);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.CardLayout(100, 20));

        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "ISBN", "Título", "Autor", "Ano", "Total", "Disponíveis"
                }));
        jScrollPane1.setViewportView(tabelaLivros);

        jPanel2.add(jScrollPane1, "card2");

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(1, 40, 30));

        btnNovo.setText("+ Novo Livro");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        jPanel3.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        jPanel3.add(btnEditar);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);
        jPanel3.add(btnExcluir);

        btnAddCopia.setText("+ Cópia");
        btnAddCopia.addActionListener(this::btnAddCopiaActionPerformed);
        jPanel3.add(btnAddCopia);

        btnRemCopia.setText("− Cópia");
        btnRemCopia.addActionListener(this::btnRemCopiaActionPerformed);
        jPanel3.add(btnRemCopia);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    public LivroView() {
        initComponents();
        estilizarCabecalho();
        estilizarPagina();
        setPreferredSize(null);
        setMinimumSize(null);
        carregarTabela();
    }

    private LivroController livroController = new LivroController();
    private models.Usuario usuarioLogado;

    public void setUsuarioLogado(models.Usuario usuario) {
        this.usuarioLogado = usuario;
    }

    private void estilizarPagina() {
        setBackground(new java.awt.Color(247, 248, 250));

        jPanel2.setBackground(new java.awt.Color(247, 248, 250));

        jPanel3.setBackground(new java.awt.Color(247, 248, 250));

        estilizarBotao(btnExcluir, new java.awt.Color(230, 57, 70));
        estilizarBotao(btnRemCopia, new java.awt.Color(230, 57, 70));

        estilizarBotao(btnEditar, new java.awt.Color(46, 196, 182));
        estilizarBotao(btnAddCopia, new java.awt.Color(46, 196, 182));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(229, 231, 235)));

        tabelaLivros.getTableHeader().setBackground(new java.awt.Color(26, 26, 46));
        tabelaLivros.getTableHeader().setForeground(java.awt.Color.WHITE);
        tabelaLivros.getTableHeader().setFont(
                new java.awt.Font("SansSerif", java.awt.Font.BOLD, 12));
        tabelaLivros.setRowHeight(32);
        tabelaLivros.setGridColor(new java.awt.Color(229, 231, 235));
    }

    private void estilizarCabecalho() {

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        estilizarBotao(btnNovo, new java.awt.Color(67, 97, 238));
    }

    private void estilizarBotao(javax.swing.JButton btn, java.awt.Color cor) {
        btn.setBackground(cor);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
    }

    private void campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoBuscaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campoBuscaActionPerformed

    public void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaLivros.getModel();
        modelo.setRowCount(0);
        for (Livro l : livroController.listarLivros()) {
            modelo.addRow(new Object[] {
                    l.getIsbn(), l.getTitulo(), l.getAutor(),
                    l.getAnoPublicacao(), l.getNumeroCopias(), l.getDisponiveis()
            });
        }
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
        int row = tabelaLivros.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um livro para editar.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String isbn = tabelaLivros.getModel().getValueAt(row, 0).toString();
        Livro livro = livroController.buscarPorIsbn(isbn);
        if (livro == null) {
            JOptionPane.showMessageDialog(this, "Livro não encontrado.");
            return;
        }

        JDialog dialog = new JDialog();
        dialog.setTitle("Editar Livro");
        dialog.setSize(400, 350);
        dialog.setModal(true);
        dialog.setLocationRelativeTo(this);

        JPanel painel = new JPanel(new GridLayout(7, 2, 10, 10));
        painel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JTextField fIsbn = new JTextField(isbn);
        fIsbn.setEditable(false);
        JTextField fTitulo = new JTextField(livro.getTitulo());
        JTextField fAutor = new JTextField(livro.getAutor());
        JTextField fAno = new JTextField(String.valueOf(livro.getAnoPublicacao()));
        JTextField fCopias = new JTextField(String.valueOf(livro.getNumeroCopias()));
        JTextField fDisponiveis = new JTextField(String.valueOf(livro.getDisponiveis()));

        painel.add(new JLabel("ISBN:"));
        painel.add(fIsbn);
        painel.add(new JLabel("Título:"));
        painel.add(fTitulo);
        painel.add(new JLabel("Autor:"));
        painel.add(fAutor);
        painel.add(new JLabel("Ano:"));
        painel.add(fAno);
        painel.add(new JLabel("Total Cópias:"));
        painel.add(fCopias);
        painel.add(new JLabel("Disponíveis:"));
        painel.add(fDisponiveis);

        JButton btnSalvar = new JButton("Salvar");
        btnSalvar.setBackground(new java.awt.Color(67, 97, 238));
        btnSalvar.setForeground(java.awt.Color.WHITE);
        btnSalvar.setBorderPainted(false);

        btnSalvar.addActionListener(e -> {
            try {
                int ano = Integer.parseInt(fAno.getText().trim());
                int copias = Integer.parseInt(fCopias.getText().trim());
                int disp = Integer.parseInt(fDisponiveis.getText().trim());
                if (disp > copias) {
                    JOptionPane.showMessageDialog(dialog, "Disponíveis não pode exceder o total.");
                    return;
                }
                boolean sucesso = livroController.editarLivro(
                        usuarioLogado,
                        isbn,
                        fTitulo.getText().trim(),
                        fAutor.getText().trim(),
                        ano, copias, disp);
                if (sucesso) {
                    carregarTabela();
                    JOptionPane.showMessageDialog(dialog, "Livro atualizado!", "Sucesso",
                            JOptionPane.INFORMATION_MESSAGE);
                    dialog.dispose();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Ano, cópias e disponíveis devem ser números.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        });

        painel.add(new JLabel());
        painel.add(btnSalvar);

        dialog.add(painel);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnEditarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNovoActionPerformed
        javax.swing.JDialog dialog = new javax.swing.JDialog();
        dialog.setTitle("Novo Livro");
        dialog.setSize(400, 320);
        dialog.setModal(true);
        dialog.setLocationRelativeTo(this);

        javax.swing.JPanel painel = new javax.swing.JPanel(new java.awt.GridLayout(6, 2, 10, 10));
        painel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        javax.swing.JTextField fIsbn = new javax.swing.JTextField();
        javax.swing.JTextField fTitulo = new javax.swing.JTextField();
        javax.swing.JTextField fAutor = new javax.swing.JTextField();
        javax.swing.JTextField fAno = new javax.swing.JTextField();
        javax.swing.JTextField fCopias = new javax.swing.JTextField();

        painel.add(new javax.swing.JLabel("ISBN:"));
        painel.add(fIsbn);
        painel.add(new javax.swing.JLabel("Título:"));
        painel.add(fTitulo);
        painel.add(new javax.swing.JLabel("Autor:"));
        painel.add(fAutor);
        painel.add(new javax.swing.JLabel("Ano:"));
        painel.add(fAno);
        painel.add(new javax.swing.JLabel("Cópias:"));
        painel.add(fCopias);

        javax.swing.JButton btnSalvar = new javax.swing.JButton("Salvar");
        btnSalvar.setBackground(new java.awt.Color(67, 97, 238));
        btnSalvar.setForeground(java.awt.Color.WHITE);
        btnSalvar.setBorderPainted(false);

        btnSalvar.addActionListener(e -> {
            if (fIsbn.getText().trim().isEmpty() || fTitulo.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(dialog,
                        "ISBN e Título são obrigatórios!", "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                int ano = Integer.parseInt(fAno.getText().trim());
                int copias = Integer.parseInt(fCopias.getText().trim());

                boolean sucesso = livroController.cadastrarLivro(
                        usuarioLogado,
                        fIsbn.getText().trim(),
                        fTitulo.getText().trim(),
                        fAutor.getText().trim(),
                        ano, copias);

                if (sucesso) {
                    carregarTabela();
                    javax.swing.JOptionPane.showMessageDialog(dialog,
                            "Livro cadastrado!", "Sucesso",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    dialog.dispose();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(dialog,
                            "Sem permissão ou dados inválidos.", "Erro",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(dialog,
                        "Ano e Cópias devem ser números!", "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        });

        painel.add(new javax.swing.JLabel());
        painel.add(btnSalvar);
        dialog.add(painel);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirActionPerformed
        int row = tabelaLivros.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um livro.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String isbn = tabelaLivros.getModel().getValueAt(row, 0).toString();
        String titulo = tabelaLivros.getModel().getValueAt(row, 1).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Excluir \"" + titulo + "\"?", "Confirmar",
                JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Livro livro = livroController.buscarPorIsbn(isbn);
            if (livro != null) {
                boolean sucesso = livroController.removerLivro(usuarioLogado, livro);
                if (sucesso) {
                    carregarTabela();
                    JOptionPane.showMessageDialog(this, "Livro excluído!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }// GEN-LAST:event_btnExcluirActionPerformed

    private void btnAddCopiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddCopiaActionPerformed
        int row = tabelaLivros.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um livro.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String isbn = tabelaLivros.getModel().getValueAt(row, 0).toString();
        Livro livro = livroController.buscarPorIsbn(isbn);
        if (livro != null) {
            livroController.adicionarCopias(usuarioLogado, livro, 1);
            carregarTabela();
            JOptionPane.showMessageDialog(this, "Cópia adicionada!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }// GEN-LAST:event_btnAddCopiaActionPerformed

    private void btnRemCopiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRemCopiaActionPerformed
        int row = tabelaLivros.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um livro.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String isbn = tabelaLivros.getModel().getValueAt(row, 0).toString();
        Livro livro = livroController.buscarPorIsbn(isbn);
        if (livro != null) {
            livroController.removerCopias(usuarioLogado, livro, 1);
            carregarTabela();
            JOptionPane.showMessageDialog(this, "Cópia removida!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }// GEN-LAST:event_btnRemCopiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LivroView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCopia;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemCopia;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabelaLivros;
    // End of variables declaration//GEN-END:variables
}
