/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author ronierejr
 */
public class MainView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSidebar = new javax.swing.JPanel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        btnMembros = new javax.swing.JButton();
        btnBibliotecarios = new javax.swing.JButton();
        btnEmprestimos = new javax.swing.JButton();
        btnLivros = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        painelConteudo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 680));

        painelSidebar.setBackground(new java.awt.Color(102, 102, 255));
        painelSidebar.setPreferredSize(new java.awt.Dimension(123, 200));

        lblNomeUsuario.setFont(new java.awt.Font("Adwaita Mono", 1, 13)); // NOI18N
        lblNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeUsuario.setText("Usuário");
        lblNomeUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCargo.setFont(new java.awt.Font("Adwaita Mono", 1, 13)); // NOI18N
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargo.setText("Cargo");
        lblCargo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnMembros.setFont(new java.awt.Font("Adwaita Sans", 0, 13)); // NOI18N
        btnMembros.setText(" Membros");
        btnMembros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnBibliotecarios.setFont(new java.awt.Font("Adwaita Sans", 0, 13)); // NOI18N
        btnBibliotecarios.setText("Bibliotecários");
        btnBibliotecarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBibliotecarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecariosActionPerformed(evt);
            }
        });

        btnEmprestimos.setFont(new java.awt.Font("Adwaita Sans", 0, 13)); // NOI18N
        btnEmprestimos.setText("📋 Empréstimos");
        btnEmprestimos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLivros.setFont(new java.awt.Font("Adwaita Sans", 0, 13)); // NOI18N
        btnLivros.setText("📚 Livros");
        btnLivros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrosActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Adwaita Sans", 0, 13)); // NOI18N
        btnSair.setText("⇠ Sair");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painelSidebarLayout = new javax.swing.GroupLayout(painelSidebar);
        painelSidebar.setLayout(painelSidebarLayout);
        painelSidebarLayout.setHorizontalGroup(
            painelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnEmprestimos)
                    .addComponent(btnBibliotecarios)
                    .addComponent(btnLivros)
                    .addComponent(btnSair)
                    .addComponent(lblNomeUsuario)
                    .addComponent(lblCargo)
                    .addComponent(btnMembros))
                .addGap(19, 19, 19))
        );

        painelSidebarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBibliotecarios, btnEmprestimos, btnLivros, btnMembros, btnSair, lblCargo, lblNomeUsuario});

        painelSidebarLayout.setVerticalGroup(
            painelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSidebarLayout.createSequentialGroup()
                .addComponent(lblNomeUsuario)
                .addGap(0, 0, 0)
                .addComponent(lblCargo)
                .addGap(0, 0, 0)
                .addComponent(btnMembros)
                .addGap(0, 0, 0)
                .addComponent(btnBibliotecarios)
                .addGap(0, 0, 0)
                .addComponent(btnEmprestimos)
                .addGap(0, 0, 0)
                .addComponent(btnLivros)
                .addGap(0, 0, 0)
                .addComponent(btnSair))
        );

        btnMembros.getAccessibleContext().setAccessibleDescription("");
        btnBibliotecarios.getAccessibleContext().setAccessibleDescription("");
        btnEmprestimos.getAccessibleContext().setAccessibleDescription("");
        btnLivros.getAccessibleContext().setAccessibleDescription("");
        btnSair.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(painelSidebar, java.awt.BorderLayout.WEST);

        getContentPane().add(painelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBibliotecariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBibliotecariosActionPerformed

    private void btnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLivrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBibliotecarios;
    private javax.swing.JButton btnEmprestimos;
    private javax.swing.JButton btnLivros;
    private javax.swing.JButton btnMembros;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JPanel painelSidebar;
    // End of variables declaration//GEN-END:variables
}
