/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import controllers.MembroController;
import models.Membro;

/**
 *
 * @author ronierejr
 */
public class MembroView extends javax.swing.JPanel {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MembroView.class.getName());

    /**
     * Creates new form MembroView
     */
    public MembroView() {
        initComponents();
        estilizarCabecalho();
        estilizarPagina();
        carregarTabela();
    }

    private MembroController membroController = new MembroController();
    private models.Usuario usuarioLogado;

    public void setUsuarioLogado(models.Usuario usuario) {
        this.usuarioLogado = usuario;
    }

    private void estilizarPagina() {
        setBackground(new java.awt.Color(247, 248, 250));

        jPanel2.setBackground(new java.awt.Color(247, 248, 250));

        jPanel3.setBackground(new java.awt.Color(247, 248, 250));

        estilizarBotao(btnDesativar, new java.awt.Color(230, 57, 70));

        estilizarBotao(btnEditar, new java.awt.Color(46, 196, 182));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(229, 231, 235)));

        tabelaMembros.getTableHeader().setBackground(new java.awt.Color(26, 26, 46));
        tabelaMembros.getTableHeader().setForeground(java.awt.Color.WHITE);
        tabelaMembros.getTableHeader().setFont(
                new java.awt.Font("SansSerif", java.awt.Font.BOLD, 12));
        tabelaMembros.setRowHeight(32);
        tabelaMembros.setGridColor(new java.awt.Color(229, 231, 235));
    }

    private void estilizarCabecalho() {

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        estilizarBotao(btnNovo, new java.awt.Color(67, 97, 238));
        estilizarBotao(btnTodos, new java.awt.Color(67, 97, 238));
        estilizarBotao(btnSuspensos, new java.awt.Color(230, 57, 70));
    }

    private void estilizarBotao(javax.swing.JButton btn, java.awt.Color cor) {
        btn.setBackground(cor);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnTodos = new javax.swing.JButton();
        btnSuspensos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMembros = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDesativar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 680));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        lblTitulo.setFont(new java.awt.Font("Adwaita Mono", 1, 24)); // NOI18N
        lblTitulo.setText("Membros");
        jPanel4.add(lblTitulo);

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        btnTodos.setText("Todos");
        btnTodos.addActionListener(this::btnTodosActionPerformed);
        jPanel5.add(btnTodos);

        btnSuspensos.setText("Suspensos");
        btnSuspensos.addActionListener(this::btnSuspensosActionPerformed);
        jPanel5.add(btnSuspensos);

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.CardLayout(100, 20));

        tabelaMembros.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "CPF", "Nome", "Email", "Telefone", "Status"
                }));
        jScrollPane1.setViewportView(tabelaMembros);

        jPanel2.add(jScrollPane1, "card2");

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(1, 40, 30));

        btnNovo.setText("+ Novo Membro");
        btnNovo.addActionListener(this::btnNovoActionPerformed);
        jPanel3.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);
        jPanel3.add(btnEditar);

        btnDesativar.setText("Desativar");
        btnDesativar.addActionListener(this::btnDesativarActionPerformed);
        jPanel3.add(btnDesativar);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    public void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaMembros.getModel();
        modelo.setRowCount(0);
        for (Membro m : membroController.listarMembros()) {
            modelo.addRow(new Object[] {
                    m.getCpf(), m.getNome(), m.getEmail(),
                    m.getTelefone(), m.isAtivo() ? "Ativo" : "Inativo"
            });
        }
    }

    private void btnDesativarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDesativarActionPerformed
        int row = tabelaMembros.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um membro.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String cpf = tabelaMembros.getModel().getValueAt(row, 0).toString();
        Membro membro = membroController.buscarPorCpf(cpf);
        if (membro != null) {
            int confirm = JOptionPane.showConfirmDialog(this, "Desativar " + membro.getNome() + "?", "Confirmar",
                    JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                membroController.desativarMembro(usuarioLogado, membro);
                carregarTabela();
                JOptionPane.showMessageDialog(this, "Membro desativado!");
            }
        }
    }// GEN-LAST:event_btnDesativarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
        int row = tabelaMembros.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um membro para editar.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String cpf = tabelaMembros.getModel().getValueAt(row, 0).toString();
        Membro membro = membroController.buscarPorCpf(cpf);
        if (membro == null) {
            JOptionPane.showMessageDialog(this, "Membro não encontrado.");
            return;
        }

        JDialog dialog = new JDialog();
        dialog.setTitle("Editar Membro");
        dialog.setSize(400, 350);
        dialog.setModal(true);
        dialog.setLocationRelativeTo(this);

        JPanel painel = new JPanel(new GridLayout(6, 2, 10, 10));
        painel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JTextField fCpf = new JTextField(cpf);
        fCpf.setEditable(false);
        JTextField fNome = new JTextField(membro.getNome());
        JTextField fEmail = new JTextField(membro.getEmail());
        JTextField fTelefone = new JTextField(membro.getTelefone());
        JTextField fEndereco = new JTextField(membro.getEndereco());
        JPasswordField fSenha = new JPasswordField();

        painel.add(new JLabel("CPF:"));
        painel.add(fCpf);
        painel.add(new JLabel("Nome:"));
        painel.add(fNome);
        painel.add(new JLabel("Email:"));
        painel.add(fEmail);
        painel.add(new JLabel("Telefone:"));
        painel.add(fTelefone);
        painel.add(new JLabel("Endereço:"));
        painel.add(fEndereco);
        painel.add(new JLabel("Senha:"));
        painel.add(fSenha);

        JButton btnSalvar = new JButton("Salvar");
        btnSalvar.addActionListener(e -> {
            String senha = new String(fSenha.getPassword());
            if (senha.isEmpty())
                senha = membro.getSenha();
            boolean sucesso = membroController.editarMembro(
                    usuarioLogado, membro,
                    fNome.getText().trim(), membro.getLogin(), senha,
                    membro.isAtivo(),
                    fEndereco.getText().trim(), fTelefone.getText().trim(), fEmail.getText().trim());
            if (sucesso) {
                carregarTabela();
                JOptionPane.showMessageDialog(dialog, "Membro atualizado!");
                dialog.dispose();
            }
        });

        painel.add(new JLabel());
        painel.add(btnSalvar);
        dialog.add(painel);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnEditarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNovoActionPerformed
        javax.swing.JDialog dialog = new javax.swing.JDialog();
        dialog.setTitle("Novo Membro");
        dialog.setSize(420, 380);
        dialog.setModal(true);
        dialog.setLocationRelativeTo(this);

        javax.swing.JPanel painel = new javax.swing.JPanel(new java.awt.GridLayout(8, 2, 10, 10));
        painel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        javax.swing.JTextField fNome = new javax.swing.JTextField();
        javax.swing.JTextField fCpf = new javax.swing.JTextField();
        javax.swing.JTextField fLogin = new javax.swing.JTextField();
        javax.swing.JPasswordField fSenha = new javax.swing.JPasswordField();
        javax.swing.JTextField fEnd = new javax.swing.JTextField();
        javax.swing.JTextField fTel = new javax.swing.JTextField();
        javax.swing.JTextField fEmail = new javax.swing.JTextField();

        painel.add(new javax.swing.JLabel("Nome:"));
        painel.add(fNome);
        painel.add(new javax.swing.JLabel("CPF:"));
        painel.add(fCpf);
        painel.add(new javax.swing.JLabel("Login:"));
        painel.add(fLogin);
        painel.add(new javax.swing.JLabel("Senha:"));
        painel.add(fSenha);
        painel.add(new javax.swing.JLabel("Endereço:"));
        painel.add(fEnd);
        painel.add(new javax.swing.JLabel("Telefone:"));
        painel.add(fTel);
        painel.add(new javax.swing.JLabel("Email:"));
        painel.add(fEmail);

        javax.swing.JButton btnSalvar = new javax.swing.JButton("Salvar");
        btnSalvar.setBackground(new java.awt.Color(67, 97, 238));
        btnSalvar.setForeground(java.awt.Color.WHITE);
        btnSalvar.setBorderPainted(false);

        btnSalvar.addActionListener(e -> {
            if (fNome.getText().trim().isEmpty() || fCpf.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(dialog,
                        "Nome e CPF são obrigatórios!", "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            boolean sucesso = membroController.cadastrarMembro(
                    usuarioLogado,
                    fNome.getText().trim(), fCpf.getText().trim(),
                    fLogin.getText().trim(), new String(fSenha.getPassword()),
                    fEnd.getText().trim(), fTel.getText().trim(),
                    fEmail.getText().trim());

            if (sucesso) {
                carregarTabela();
                javax.swing.JOptionPane.showMessageDialog(dialog,
                        "Membro cadastrado!", "Sucesso",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                dialog.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(dialog,
                        "Sem permissão ou dados inválidos.", "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        });

        painel.add(new javax.swing.JLabel());
        painel.add(btnSalvar);
        dialog.add(painel);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnNovoActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTodosActionPerformed
        carregarTabela();
    }// GEN-LAST:event_btnTodosActionPerformed

    private void btnSuspensosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuspensosActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabelaMembros.getModel();
        modelo.setRowCount(0);
        for (Membro m : membroController.listarMembrosSuspensos()) {
            modelo.addRow(new Object[] {
                    m.getCpf(), m.getNome(), m.getEmail(),
                    m.getTelefone(), "Suspenso"
            });
        }
    }// GEN-LAST:event_btnSuspensosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MembroView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesativar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSuspensos;
    private javax.swing.JButton btnTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabelaMembros;
    // End of variables declaration//GEN-END:variables
}
